name: Build with Multiple JDKs

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [8, 11, 16] # Specifica le versioni di Java che desideri testare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build and Test
        run: mvn -B package --file pom.xml
